 
eureka:
   client:
      serviceUrl:
           defaultZone: http://localhost:8761/eureka
           
eureka:
   client:
     instance:
         preferIpAddress: true
 
server:
   port:${PORT:${SERVER_PORT:0}}     
   
words: I,You,He,She,It
